// Release/manifest sanity checks: version parity, required files, 500 LOC cap,
// Lisa's Dungeon branding, and no leftover AI-assistance branding.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.join(__dirname, '..');
const EXCLUDED_DIRS = new Set(['.git', 'node_modules', 'zips', 'tests']);
const LOC_CAP = 500;

const FORBIDDEN_PATTERNS = [
  /\bclaude\b/i,
  /\bchatgpt\b/i,
  /\bcopilot\b/i,
  /\banthropic\b/i,
  /\bopenai\b/i,
  /ai-assisted/i,
  /generated by ai/i
];

function collectFiles(dir, pred) {
  const files = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      if (EXCLUDED_DIRS.has(entry.name)) continue;
      files.push(...collectFiles(path.join(dir, entry.name), pred));
    } else if (pred(entry.name)) {
      files.push(path.join(dir, entry.name));
    }
  }
  return files;
}

function validateModule() {
  const errors = [];
  const packageJson = JSON.parse(fs.readFileSync(path.join(projectRoot, 'package.json'), 'utf8'));
  const moduleJson = JSON.parse(fs.readFileSync(path.join(projectRoot, 'module.json'), 'utf8'));

  if (packageJson.version !== moduleJson.version) {
    errors.push(`Version mismatch: package.json (${packageJson.version}) vs module.json (${moduleJson.version})`);
  }
  if (!String(moduleJson.id || '').startsWith('ld-')) {
    errors.push(`module.json id must start with ld- (got ${moduleJson.id})`);
  }
  const authorName = moduleJson.authors?.[0]?.name;
  if (authorName !== "Lisa's Dungeon") {
    errors.push(`module.json author must be Lisa's Dungeon (got ${authorName})`);
  }

  for (const file of ['package.json', 'module.json', 'LICENSE', 'README.md', 'CHANGELOG.md']) {
    if (!fs.existsSync(path.join(projectRoot, file))) {
      errors.push(`Missing required file: ${file}`);
    }
  }

  const codeFiles = collectFiles(projectRoot, (name) => /\.(js|mjs|css)$/.test(name));
  for (const file of codeFiles) {
    const lineCount = fs.readFileSync(file, 'utf8').split('\n').length;
    if (lineCount > LOC_CAP) {
      errors.push(`${path.relative(projectRoot, file)} exceeds the ${LOC_CAP} LOC cap (${lineCount} lines)`);
    }
  }

  const textFiles = collectFiles(projectRoot, (name) => /\.(js|mjs|json|md|html|hbs|css)$/.test(name));
  for (const file of textFiles) {
    const content = fs.readFileSync(file, 'utf8');
    for (const pattern of FORBIDDEN_PATTERNS) {
      if (pattern.test(content)) {
        errors.push(`Found forbidden pattern ${pattern} in ${path.relative(projectRoot, file)}`);
      }
    }
  }

  if (errors.length > 0) {
    console.error('Validation failed:');
    errors.forEach((error) => console.error(`  - ${error}`));
    process.exit(1);
  }
  console.log(`Validation passed for ${packageJson.name} ${packageJson.version}`);
}

validateModule();
